FROM rasa/rasa:3.2.6-full
RUN git clone https://github.com/ruthenian8/rasa_sample_project.git
WORKDIR /app/rasa_sample_project # fixed random_seed in the config file
RUN rasa train nlu --out=/app/models
WORKDIR /app
ENTRYPOINT rasa run --enable-api -m models/$(ls /app/models) --auth $RASA_API_KEY
