FROM apache/superset:2.1.0rc1
USER root
RUN cd /app && pip install .[clickhouse]
COPY entrypoint_stats.sh /app/docker/
COPY --chown=superset superset_config_docker.py /app/pythonpath/
ENV SUPERSET_CONFIG_PATH /app/pythonpath/superset_config_docker.py
USER superset
ENTRYPOINT ["/bin/bash","/app/docker/entrypoint_stats.sh"]