FROM python:3.12.0-alpine3.18

ARG SERVICE_HOST
ENV SERVICE_HOST ${SERVICE_HOST}

ARG SERVICE_PORT
ENV SERVICE_PORT ${SERVICE_PORT}

WORKDIR /src
RUN pip install requests

COPY ./client.py /src
CMD python3 client.py
