version: 2
updates:

  - package-ecosystem: "docker"
    directory: "/"
    target-branch: dev
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    groups:
      docker-deps:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: dev
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    groups:
      action-deps:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    target-branch: dev
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    labels:
      - "dependencies"
    groups:
      deps:
        patterns:
          - "*"
