[project]
name = "chatsky"
version = "0.10.0"
description = "Chatsky is a free and open-source software stack for creating chatbots, released under the terms of Apache License 2.0."
license = "Apache-2.0"
authors = [
    { name = "Denis Kuznetsov", email = "kuznetsov.den.p@gmail.com" },
    { name = "Roman Zlobin", email = "RLKRo@proton.me" },
    { name = "Aleksandr Sergeev", email = "shveitsar215@gmail.com" },
    { name = "Daniil Ignatiev", email = "ruthenian8@gmail.com" },
]
maintainers = [
    { name = "Roman Zlobin", email = "RLKRo@proton.me" },
    { name = "Andrey Chirkin" },
    { name = "Alexandra Dolidze" },
]
readme = "README.md"
keywords = ["chatbots"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3 :: Only",
]

requires-python = "^3.9,!=3.9.7"  # `streamlit` package does not support python 3.9.7
dependencies = [
    "pydantic>=2.0",
    "nest-asyncio",
    "typing-extensions",
    "eval_type_backport",
    "wrapt",
    "colorama",
]

[project.urls]

homepage = "https://github.com/deeppavlov/chatsky"
documentation = "https://deeppavlov.github.io/chatsky/"
"Project Template" = "https://github.com/deeppavlov/chatsky-template"

[tool.poetry]

include = [
    { path = "CONTRIBUTING.md" },
    { path = "chatsky/" },
]
exclude = [
    { path = "tests" },
    { path = "scripts" },
]

[project.optional-dependencies]
json = [ "aiofiles" ]
pickle = [ "aiofiles" ]
sqlite = [ "sqlalchemy[asyncio]", "aiosqlite" ]
redis = [ "redis" ]
mongodb = [ "motor" ]
mysql = [ "sqlalchemy[asyncio]", "asyncmy", "cryptography" ]
postgresql = [ "sqlalchemy[asyncio]", "asyncpg" ]
ydb = [ "ydb", "six" ]
telegram = [ "python-telegram-bot[all]~=21.3" ]
stats = [
    "opentelemetry-exporter-otlp>=1.20.0",  # log body serialization is required
    "opentelemetry-instrumentation",
    "requests",
    "tqdm",
    "omegaconf",
]
benchmark = [ "pympler", "humanize", "pandas", "altair", "tqdm" ]
yaml = [ "pyyaml" ]
llm = [ "langchain" ]

[tool.poetry.group.lint]
optional = true

[tool.poetry.group.lint.dependencies]
flake8 = "*"
isort = "*"
black = "*"
mypy = "*"


[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
requests = "*"
idna = "*"
pytest = "*"
pytest-cov = "*"
coverage = { version = "!=7.3.3,!=7.6.6", extras = ["toml"] }
# Coverage 7.3.3 breaks pragma: no cover -- https://github.com/nedbat/coveragepy/issues/1713
# Unable to find coverage 7.6.6 on python 3.9
pytest-asyncio = "*"
pytest-virtualenv = "*"
sniffio = "*"
h11 = "*"
aiochclient = "*"
httpx = "*"
sqlparse = "*"
jsonschema = "*"


[tool.poetry.group.devel]
optional = false

[tool.poetry.group.devel.dependencies]
urllib3 = "<2.0"  # ensure chatsky doesn't update urllib which breaks poetry
python-on-whales = "*"
python-dotenv = "*"
poethepoet = { version = "*", extras = ["poetry_plugin"] }


[tool.poetry.group.tutorials]
optional = true

[tool.poetry.group.tutorials.dependencies]
flask = { version = "*", extras = ["async"] }
psutil = "*"
telethon = "*"
fastapi = "*"
uvicorn = "*"
websockets = "*"
locust = "*"
streamlit = "*"
streamlit-chat = "*"
langchain-openai = "*"
langchain-anthropic = "*"


[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "*"
nbsphinx = "*"
sphinx-favicon = "*"
sphinx-gallery = "*"
sphinx-copybutton = "*"
sphinxcontrib-katex = "*"
pydata-sphinx-theme = "*"
sphinxcontrib-apidoc = "*"
sphinxcontrib-httpdomain = "*"
sphinx-autodoc-typehints = "*"
jupytext = "*"
jupyter = "*"


[project.scripts]
"chatsky.stats" = "chatsky.stats.__main__:main"


[tool.poe]
default_task_type = "script"

[tool.poe.tasks]
info = "scripts.misc:info"
flake = "scripts.codestyle:_run_flake"
black = "scripts.codestyle:_run_black(modify=False)"
lint.sequence = ["flake", "black"]
lint.ignore_fail = "return_non_zero"
format = "scripts.codestyle:_run_black(modify=True)"
clean_docs = "scripts.clean:clean_docs"
clean = "scripts.clean:clean"
quick_test = "scripts.test:quick_test"
quick_test_coverage = "scripts.test:quick_test_coverage"
test_no_cov = "scripts.test:test_no_cov"
test_no_deps = "scripts.test:test_no_deps"
test_all = "scripts.test:test_all"
docs = "scripts.doc:docs"
docs_no_docker = "scripts.doc:docs_no_docker"



[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"



[tool.isort]
profile = "black"



[tool.pytest.ini_options]
addopts = "--strict-markers"
markers = [
    "docker: marks tests as requiring docker containers to work",
    "slow: marks tests as slow (taking more than a minute to complete)",
    "no_coverage: tests that either cannot run inside the `coverage` workflow or do not affect coverage stats",
    "all: reserved by allow-skip",
    "none: reserved by allow-skip",
    "needs_dependencies: marks tests as requiring any extra dependencies to run"
]
asyncio_mode = "auto"

[tool.coverage.run]
concurrency = [
    "thread",
    "greenlet",
]


[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_also = [
    "if TYPE_CHECKING:",
    "raise NotImplementedError",
]
