version: '3.8'

services:
  web:
    build:
      context: web/
    volumes:
      - ./web/:/app:ro
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
  db:
    env_file: [.env]
    image: postgres:latest
    restart: unless-stopped
    healthcheck:
      test: pg_isready --username=$${POSTGRES_USERNAME}
      interval: 4s
      timeout: 3s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    image: nginx
    depends_on:
      - web
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web/static:/app/static:ro

volumes:
  postgres_data: