# syntax=docker/dockerfile:1

FROM python:3.10-slim-buster
RUN apt update && apt install -y git

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .
CMD ["python3", "run.py"]
